#!/bin/bash
# Compile-check the custom module's Java without a full Gradle project.
#
# The repo has no android/ directory (expo prebuild has never been run), so
# `gradlew` cannot be used for a quick check. This runs the real toolchain
# pieces directly:
#
#   1. aapt2  - compiles res/ and links the manifest, then generates a real
#               R.java from the resulting R.txt. This is what proves things
#               like `R.drawable.ic_studio_notification` resolve; javac alone
#               cannot see resources at all.
#   2. javac  - compiles every .java in the module against the framework jar
#               and the React Native AAR classes.jar.
#
# Usage (env vars all optional):
#   ANDROID_HOME=~/Library/Android/sdk \
#   RN_CLASSES=$(find ~/.gradle/caches -name classes.jar -path '*react-android*' | head -1) \
#   ./scripts/verify/compile-check-native.sh
set -u

ROOT=$(cd "$(dirname "$0")/../.." && pwd)
SRC="$ROOT/modules/audio-hardware-router/android/src/main"
SDK=${ANDROID_HOME:-${ANDROID_SDK_ROOT:-$HOME/android-sdk}}
ANDROID_JAR=${ANDROID_JAR:-$SDK/platforms/android-36/android.jar}
AAPT2=${AAPT2:-$(ls "$SDK"/build-tools/*/aapt2 2>/dev/null | tail -1)}
RN_CLASSES=${RN_CLASSES:-}
NAMESPACE=expo.modules.audiohardwarerouter

WORK=$(mktemp -d)
OUT="$WORK/classes"
GEN="$WORK/gen"
mkdir -p "$OUT" "$GEN/androidx/annotation" "$GEN/$NAMESPACE"
fail=0

[ -f "$ANDROID_JAR" ] || {
  echo "missing android.jar at $ANDROID_JAR (sdkmanager \"platforms;android-36\")"
  exit 2
}

CP="$ANDROID_JAR"
if [ -n "$RN_CLASSES" ] && [ -f "$RN_CLASSES" ]; then
  CP="$CP:$RN_CLASSES"
else
  echo "warning: RN_CLASSES not set - com.facebook.react imports will not resolve"
fi

# androidx.annotation is two no-op annotations; generate them instead of
# depending on a Maven mirror that may be unreachable.
printf 'package androidx.annotation;\npublic @interface NonNull {}\n' > "$GEN/androidx/annotation/NonNull.java"
printf 'package androidx.annotation;\npublic @interface Nullable {}\n' > "$GEN/androidx/annotation/Nullable.java"

# ---- resources -------------------------------------------------------------
if [ -n "$AAPT2" ] && [ -x "$AAPT2" ]; then
  # AGP declares the package in build.gradle (namespace); a standalone aapt2
  # link wants it in the manifest, so link a copy that has one.
  sed "s|<manifest |<manifest package=\"$NAMESPACE\" |" "$SRC/AndroidManifest.xml" > "$WORK/AndroidManifest.xml"
  if ! "$AAPT2" compile --dir "$SRC/res" -o "$WORK/res.zip" > "$WORK/aapt.log" 2>&1; then
    echo "aapt2 compile FAILED:"; cat "$WORK/aapt.log"; fail=1
  elif ! "$AAPT2" link -o "$WORK/check.apk" -I "$ANDROID_JAR" \
      --manifest "$WORK/AndroidManifest.xml" --auto-add-overlay \
      --output-text-symbols "$WORK/R.txt" "$WORK/res.zip" >> "$WORK/aapt.log" 2>&1; then
    echo "aapt2 link FAILED:"; cat "$WORK/aapt.log"; fail=1
  else
    echo "aapt2: res/ compiled and manifest linked"
    python3 - "$WORK/R.txt" "$GEN/$NAMESPACE/R.java" "$NAMESPACE" <<'PY'
import collections, sys
rtxt, out, pkg = sys.argv[1], sys.argv[2], sys.argv[3]
groups = collections.OrderedDict()
for line in open(rtxt):
    parts = line.split()
    if len(parts) == 4 and parts[0] == "int":
        groups.setdefault(parts[1], []).append((parts[2], parts[3]))
lines = [
    f"package {pkg};",
    "",
    "/** Generated by scripts/verify/compile-check-native.sh from the module's own res/. */",
    "public final class R {",
]
for kind, entries in groups.items():
    lines.append(f"    public static final class {kind} {{")
    for name, value in entries:
        lines.append(f"        public static final int {name} = {value};")
    lines.append("    }")
lines.append("}")
open(out, "w").write("\n".join(lines) + "\n")
print("R.java: " + ", ".join(f"{k}({len(v)})" for k, v in groups.items()))
PY
  fi
else
  echo "warning: aapt2 not found ($SDK/build-tools/*/aapt2) - resource ids are NOT checked"
  printf 'package %s;\npublic final class R {\n  public static final class drawable { public static final int ic_studio_notification = 1; }\n}\n' \
    "$NAMESPACE" > "$GEN/$NAMESPACE/R.java"
fi

# ---- java ------------------------------------------------------------------
find "$SRC/java" -name '*.java' > "$WORK/sources.txt"
javac -nowarn -encoding UTF-8 -classpath "$CP" -d "$OUT" \
  @"$WORK/sources.txt" "$GEN/androidx/annotation/"*.java "$GEN/$NAMESPACE/R.java" \
  2>&1 | sed "s|$WORK/||" | grep -v "^Note:" | grep -v "bootstrap class path"
rc=${PIPESTATUS[0]}
[ "$rc" -ne 0 ] && fail=1

echo "compiled $(wc -l < "$WORK/sources.txt") java files -> $(find "$OUT" -name '*.class' | wc -l) classes"
echo "JAVAC_EXIT=$rc"
exit $fail
